# Runs `faqem --digest` and compares every digest line with the recorded golden digests.
# Usage: cmake -DFAQEM=... -DINPUT=... -DARGS="--auto Medium" -DGOLDEN=... -DOUT=... -P check_golden.cmake
separate_arguments(ARGS UNIX_COMMAND "${ARGS}")
file(REMOVE_RECURSE "${OUT}")
execute_process(COMMAND "${FAQEM}" "${INPUT}" ${ARGS} --digest -o "${OUT}"
                OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "faqem failed (${rc}):\n${stdout}\n${stderr}")
endif()
string(REPLACE "\n" ";" lines "${stdout}")
set(actual "")
foreach(line IN LISTS lines)
  if(line MATCHES "^digest (.*)$")
    list(APPEND actual "${CMAKE_MATCH_1}")
  endif()
endforeach()
file(STRINGS "${GOLDEN}" expected)
list(SORT actual)
list(SORT expected)
if(NOT actual STREQUAL expected)
  string(REPLACE ";" "\n" a "${actual}")
  string(REPLACE ";" "\n" e "${expected}")
  message(FATAL_ERROR "Digests differ from our engine.\nexpected:\n${e}\nactual:\n${a}")
endif()
list(LENGTH expected n)
message(STATUS "all ${n} digests identical to our engine")
